[package]
name = "eytzinger-interpolation"
description = "Eytzinger array layout with interpolative search support"
license = "MIT"
documentation = "https://docs.rs/eytzinger-interpolation"
repository = "https://github.com/sanity/eytzinger-interpolation"
version = "1.0.1"
authors = ["main() <main@ehvag.de>", "Andre Popovitch <andre@popovit.ch>"]
edition = "2021"

[profile.release]
debug = true

[dependencies.nonmax]
version = "0.5"
optional = true

[dependencies.nohash-hasher]
version = "0.2"
optional = true

[dev-dependencies]
quickcheck = "0.4"

[features]
default = ["heap-permutator", "heap-permutator-sparse"]
heap-permutator = ["nonmax"]
heap-permutator-sparse = ["nohash-hasher"]
branchless = []
